### ISSUE TITLE
Fastlane error

### ISSUE THREAD

**Issue by IzzySoft** [SkyTubeTeam/SkyTubeLegacy#1]
Your app just got listed at F-Droid.org – congrats! It just came without a summary. Someone played wild-west in the Fastlane structures, so can you please call the sheriff and have him `git mv shot_description.txt short_description.txt`? Thanks!

**Comment by gzsombor** [comment]
Thanks for opening the ticket, the file was there for SkyTube for years, and nobody noticed it. I've just [cherry-picked](https://github.com/SkyTubeTeam/SkyTubeLegacy/commit/4e15649f4eba95186ac8cefdfb1a2db7ac7c0e90) the fix for it.

**Comment by IzzySoft** [comment]
Thanks for the fast fix! Summary should show up then at F-Droid with the next release. I was just informed the other SkyTube client had the same issue – I didn't check but assume you've fixed it along, just mentioning in case it was missed.
